apiVersion: dapr.io/v1alpha
kind: Component
metadata: 
  name: ecommercepubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6379
    - name: redisPassword
      value: ""