apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: users
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: initialOffset
      value: "oldest" # if you wanted to say ignore all the old ones, just start from when this goes online, change it to newest.
    - name: brokers # Required. Kafka broker connection setting
      value: "localhost:9092"
    - name: clientID # Optional. Used as client tracing ID by Kafka brokers.
      value: "users"
    - name: authType # Required.
      value: "none"
    - name: disableTls # Optional. Disable TLS. This is not safe for production!! You should read the `Mutual TLS` section for how to use TLS.
      value: "true"
